# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 10:57
from __future__ import unicode_literals

import banners.models
from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=255, verbose_name='\u94fe\u63a5')),
                ('linkarray', models.TextField(blank=True, default='', null=True, verbose_name='Linkarray')),
                ('image', models.ImageField(upload_to=banners.models.get_banner_image_upload_path, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('alt', models.CharField(help_text='\u56fe\u7247\u65e0\u6cd5\u663e\u793a\u65f6\u5c06\u7528\u8be5\u6587\u5b57\u4ee3\u66ff', max_length=255, verbose_name='\u56fe\u7247\u6587\u672c')),
                ('title', models.CharField(default='', max_length=255, verbose_name='\u6807\u9898')),
                ('type', models.CharField(blank=True, default='', max_length=50, verbose_name='\u7c7b\u578b')),
                ('map', models.TextField(blank=True, verbose_name='Map')),
                ('visibility', models.IntegerField(choices=[(1, '\u53ef\u89c1'), (0, '\u4e0d\u53ef\u89c1')], default=1, verbose_name='\u662f\u5426\u53ef\u89c1')),
                ('position', models.IntegerField(help_text='\u6392\u5e8f:\u6570\u5b57\u8d8a\u5c0f\u6392\u5728\u8d8a\u524d', verbose_name='\u6392\u5e8f')),
                ('lang', models.CharField(blank=True, default='', max_length=10, verbose_name='\u8bed\u79cd')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6a2a\u5e45\u5e7f\u544a',
                'verbose_name_plural': '\u6a2a\u5e45\u5e7f\u544a',
            },
        ),
    ]
