# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 10:57
from __future__ import unicode_literals

import carts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('key', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('is_cart', models.IntegerField(default=1, verbose_name='1:\u8d2d\u7269\u8f66,0:save for later')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True)),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66\u4ea7\u54c1',
                'verbose_name_plural': '\u8d2d\u7269\u8f66\u4ea7\u54c1',
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
                ('value', models.FloatField(default=0, verbose_name='\u91d1\u989d')),
                ('item_sku', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4fc3\u9500\u4ea7\u54c1SKU')),
                ('type', models.IntegerField(choices=[(1, '\u51cf\u6298\u6263'), (2, '\u51cf\u4ef7'), (3, '\u8d60\u54c1')], default=0, verbose_name='\u6298\u6263\u7c7b\u578b')),
                ('target', models.CharField(blank=True, choices=[('1', '\u662f'), ('0', '\u5426')], default=0, max_length=50, null=True, verbose_name='\u6253\u6298\u4ea7\u54c1\u901a\u7528')),
                ('on_show', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='\u662f\u5426\u4e3a\u6240\u6709\u5ba2\u6237\u516c\u7528')),
                ('limit', models.IntegerField(blank=True, default=0, help_text='(* \u82e5\u6b21\u6570\u503c\u4e3a -1 \u5219\u4e3a\u65e0\u9650\u4f7f\u7528\uff01)', null=True, verbose_name='\u53ef\u4f7f\u7528\u6b21\u6570')),
                ('effective_limit', models.IntegerField(default=0, help_text='\u53ea\u6709\u9650\u5236\u7c7b\u522b\u6216\u4ea7\u54c1\u65f6\u6709\u6548(-1\u4e3a\u4e0d\u9650\u5236)', verbose_name='\u5bf9\u4ea7\u54c1\u4f7f\u7528\u6b21\u6570')),
                ('used', models.IntegerField(default=0, verbose_name='\u5df2\u4f7f\u7528\u6b21\u6570')),
                ('usedfor', models.IntegerField(blank=True, choices=[(1, '\u6ce8\u518c\u7cfb\u7edf\u6298\u6263'), (2, '\u7f51\u7ad9\u6d3b\u52a8\u4fc3\u9500'), (3, '\u6279\u53d1\u4f63\u91d1\u6298\u6263'), (4, '\u5ba2\u670d\u552e\u540e\u8865\u507f'), (5, '\u5ba2\u670d\u552e\u524d\u6298\u6263'), (6, '\u63a8\u5e7f\u5408\u4f5c\u6298\u6263'), (7, '\u63a8\u5e7f\u6d3b\u52a8\u6298\u6263'), (8, '\u8054\u76df\u4f18\u60e0\u6298\u6263'), (9, '\u7ea2\u4eba\u535a\u5ba2giveaway'), (10, '404\u9875\u9762\u6298\u6263\u53f7'), (11, '\u8d2d\u7269\u8f66\u4e13\u5c5e\u6298\u6263(\u52ff\u7528)'), (12, '\u6d4b\u8bd5\u5355\u7528'), (13, 'VIP \u5ba2\u6237\u6298\u6263'), (14, 'youtube\u7ea2\u4eba\u4e13\u5c5e\u6298\u6263\u53f7'), (15, '\u7ea2\u4eba\u9000\u6b3e'), (16, 'EDM\u8001\u5ba2\u6237\u7ef4\u62a4'), (17, 'FB GIVEAWAY'), (18, 'polyvore contest'), (19, 'instagram\u9996\u9875')], default=0, null=True, verbose_name='\u6298\u6263\u7528\u9014')),
                ('product_limit', models.CharField(blank=True, help_text='\u586b\u5165\u4ea7\u54c1ID\uff0c\u591a\u4e2aID\u4ee5\u9017\u53f7\u5206\u9694', max_length=200, null=True, verbose_name='\u4ea7\u54c1\u9650\u5236')),
                ('catalog_limit', models.CharField(blank=True, help_text='\u586b\u5165\u7c7b\u522bID\uff0c\u591a\u4e2aID\u4ee5\u9017\u53f7\u5206\u9694', max_length=200, null=True, verbose_name='\u5206\u7c7b\u9650\u5236')),
                ('condition', models.FloatField(blank=True, default=0, null=True, verbose_name='\u6700\u4f4e\u6d88\u8d39\u9650\u5236')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('started', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('expired', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('is_mailed', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '\u6298\u6263\u53f7',
                'verbose_name_plural': '\u6298\u6263\u53f7',
            },
        ),
        migrations.CreateModel(
            name='Cpromotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True, verbose_name='\u540d\u79f0')),
                ('conditions', models.TextField(null=True, verbose_name='\u4fc3\u9500\u6761\u4ef6')),
                ('brief', models.TextField(null=True, verbose_name='\u7b80\u4ecb')),
                ('actions', models.TextField(null=True, verbose_name='\u4fc3\u9500\u65b9\u5f0f')),
                ('is_active', models.IntegerField(default=1, null=True)),
                ('from_date', django_unixdatetimefield.fields.UnixDateTimeField(verbose_name='\u8d77\u59cb\u65f6\u95f4')),
                ('to_date', django_unixdatetimefield.fields.UnixDateTimeField(verbose_name='\u622a\u6b62\u65f6\u95f4')),
                ('priority', models.IntegerField(default=0, verbose_name='\u4f18\u5148\u7ea7')),
                ('stop_further_rules', models.IntegerField(default=1)),
                ('restrictions', models.TextField(null=True, verbose_name='\u5206\u7c7b/\u4ea7\u54c1\u9650\u5236')),
                ('celebrity_avoid', models.IntegerField(default=0, null=True, verbose_name='\u7ea2\u4eba\u8fc7\u6ee4')),
                ('de', models.CharField(blank=True, default='', max_length=255, verbose_name='DE\u7b80\u4ecb')),
                ('es', models.CharField(blank=True, default='', max_length=255, verbose_name='ES\u7b80\u4ecb')),
                ('fr', models.CharField(blank=True, default='', max_length=255, verbose_name='FR\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66\u4fc3\u9500',
                'verbose_name_plural': '\u8d2d\u7269\u8f66\u4fc3\u9500',
            },
        ),
        migrations.CreateModel(
            name='CustomerCoupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='Promotionfilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=0, max_length=255, verbose_name='\u5206\u7c7bid')),
                ('set', models.CharField(default=0, max_length=255, verbose_name='set id')),
                ('price_lower', models.FloatField(default=0, verbose_name='\u6700\u4f4e\u4ef7')),
                ('price_upper', models.FloatField(default=0, verbose_name='\u6700\u9ad8\u4ef7')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Name')),
                ('brief', models.TextField(blank=True, verbose_name='\u7b80\u4ecb')),
                ('filter', models.IntegerField(blank=True, default=0, null=True, verbose_name=carts.models.Promotionfilter)),
                ('actions', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('args', models.TextField(blank=True)),
                ('is_active', models.IntegerField(default=1)),
                ('is_view', models.IntegerField(default=1)),
                ('from_date', django_unixdatetimefield.fields.UnixDateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('to_date', django_unixdatetimefield.fields.UnixDateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u8ba2\u5355\u6570')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('price_lower', models.FloatField(default=0, verbose_name='\u6700\u4f4e\u4ef7')),
                ('price_upper', models.FloatField(default=0, verbose_name='\u6700\u9ad8\u4ef7')),
            ],
            options={
                'verbose_name': '\u65b0\u54c1\u6298\u6263',
                'verbose_name_plural': '\u65b0\u54c1\u6298\u6263',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('brief', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('orderby', models.IntegerField(default=1000)),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
                ('off', models.FloatField(choices=[(1.0, '100%'), (0.9, '90%'), (0.8, '80%'), (0.7, '70%'), (0.6, '60%'), (0.5, '50%'), (0.45, '45%'), (0.4, '40%')], default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Spromotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='\u4fc3\u9500\u4ef7\u683c')),
                ('type', models.IntegerField(choices=[(0, 'vip'), (1, 'daily'), (2, 'cost'), (3, 'outlet'), (4, 'special'), (5, 'activity'), (6, 'flash_sale'), (7, 'top_seller'), (-1, 'bomb')], default=4, verbose_name='\u4ea7\u54c1\u4fc3\u9500\u7c7b\u578b')),
                ('position', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6392\u5e8f')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('expired', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': '\u7279\u4ef7\u4ea7\u54c1\u4fc3\u9500',
                'verbose_name_plural': '\u4ea7\u54c1\u4fc3\u9500',
            },
        ),
    ]
