# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20170228_1057'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spromotions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='category',
            field=models.ManyToManyField(blank=True, to='products.Category', verbose_name='\u5206\u7c7bid'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='set',
            field=models.ManyToManyField(blank=True, to='products.Set', verbose_name='set id'),
        ),
        migrations.AddField(
            model_name='customercoupons',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Coupons'),
        ),
        migrations.AddField(
            model_name='customercoupons',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customers'),
        ),
        migrations.AddField(
            model_name='cpromotions',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customers'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Productitem'),
        ),
    ]
