# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('address1', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('is_default', models.BooleanField(choices=[(1, '\u9ed8\u8ba4\u5730\u5740'), (0, '\u666e\u901a\u5730\u5740')], default=0)),
            ],
            options={
                'verbose_name': '\u5730\u5740\u7ba1\u7406',
                'verbose_name_plural': '\u5730\u5740\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='\u5ba2\u6237\u90ae\u7bb1')),
                ('password', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('birthday', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('status', models.IntegerField(blank=True, choices=[(1, '\u6b63\u5e38'), (0, '\u5c4f\u853d')], db_index=True, default=1, null=True, verbose_name='\u72b6\u6001')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=1, null=True, verbose_name='\u6027\u522b')),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u79ef\u5206')),
                ('order_total', models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='\u8ba2\u5355\u603b\u91d1\u989d')),
                ('is_facebook', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, null=True, verbose_name='fb\u7528\u6237')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP')),
                ('vip_level', models.IntegerField(blank=True, default=0, null=True, verbose_name='VIP\u7b49\u7ea7')),
                ('last_login_time', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, db_index=True, null=True, verbose_name='\u6700\u540e\u4e00\u6b21\u767b\u5f55\u65f6\u95f4')),
                ('last_login_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6700\u540e\u4e00\u6b21\u767b\u5f55IP')),
                ('lang', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ppec_status', models.IntegerField(blank=True, choices=[(-1, '\u975ePPEC\u7528\u6237'), (0, 'PPEC\u7528\u6237\u6ca1\u767b\u5f55'), (1, '\u767b\u5f55\u7528\u6237')], default=0, null=True, verbose_name='PPEC\u7528\u6237\u72b6\u6001')),
                ('flag', models.IntegerField(blank=True, choices=[(0, '\u6b63\u5e38\u5ba2\u6237'), (1, '\u975e\u6b63\u5e38\u5ba2\u6237'), (3, '\u6279\u53d1\u5ba2\u6237')], default=0, null=True, verbose_name='\u987e\u5ba2\u6807\u8bc6')),
                ('is_vip', models.IntegerField(blank=True, choices=[(1, '\u662f'), (0, '\u5426')], default=1, null=True, verbose_name='VIP\u72b6\u6001')),
                ('vip_start', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u4f1a\u5458\u5f00\u59cb\u65f6\u95f4')),
                ('vip_end', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u521d\u59cb\u4f1a\u5458\u5230\u671f\u65f6\u95f4')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('give_points', models.BooleanField(default=False)),
                ('ip_country', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7ba1\u7406',
                'verbose_name_plural': '\u7528\u6237\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='\u90ae\u7bb1')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('active', models.BooleanField(default=False)),
                ('firstname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u6027\u522b')),
                ('zip', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='zipcode')),
                ('occupation', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u804c\u4e1a')),
                ('birthday', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u56fd\u5bb6')),
            ],
            options={
                'verbose_name': '\u8ba2\u9605\u7528\u6237',
                'verbose_name_plural': '\u8ba2\u9605\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='Point_Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='\u79ef\u5206\u6570\u91cf')),
                ('order_id', models.IntegerField(blank=True, default=0, null=True)),
                ('order_date', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u4e0b\u5355\u65e5\u671f')),
                ('order_num', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u8ba2\u5355\u53f7')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u79ef\u5206\u4f7f\u7528\u8bb0\u5f55',
                'verbose_name_plural': '\u79ef\u5206\u4f7f\u7528\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Point_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='\u79ef\u5206')),
                ('type', models.CharField(blank=True, choices=[('product_show', '\u4ea7\u54c1\u79c0\u79ef\u5206'), ('review', '\u8bc4\u8bba\u5956\u52b1\u79ef\u5206'), ('feedback', '\u4e92\u52a8\u53cd\u9988\u79ef\u5206'), ('promoting', '\u63a8\u5e7f\u5956\u52b1\u79ef\u5206'), ('register', '\u6ce8\u518c\u8d60\u9001\u79ef\u5206'), ('order', '\u8d2d\u7269\u8d60\u9001\u79ef\u5206'), ('affiliate', '\u4f63\u91d1\u5151\u6362\u79ef\u5206'), ('compensation', '\u8ba2\u5355\u8865\u507f\u79ef\u5206')], default='product_show', max_length=100, null=True, verbose_name='\u79ef\u5206\u7c7b\u578b')),
                ('status', models.CharField(blank=True, choices=[('activated', 'activated'), ('pending', 'pending')], default='activated', max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('order_id', models.IntegerField(blank=True, default=0, null=True)),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u79ef\u5206\u8bb0\u5f55',
                'verbose_name_plural': '\u79ef\u5206\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('token', models.CharField(max_length=40)),
                ('site_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('permalink', models.CharField(default='', max_length=255)),
                ('thumbmail', models.CharField(default='', max_length=255)),
                ('product_sku', models.CharField(default='', max_length=100)),
                ('is_mailed', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customers')),
            ],
            options={
                'verbose_name': 'wishlists',
                'verbose_name_plural': 'wishlists',
            },
        ),
    ]
