# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='\u59d3\u540d')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='\u90ae\u7bb1')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u56fd\u5bb6')),
                ('sex', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'OTHER')], default=1, verbose_name='\u6027\u522b')),
                ('birthday', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('level', models.IntegerField(default=0, verbose_name='\u4f1a\u5458\u7b49\u7ea7')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('is_able', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, default=0, null=True)),
                ('show_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u663e\u793a\u540d\u79f0')),
                ('height', models.CharField(blank=True, default='', help_text='\u5355\u4f4dcm', max_length=50, null=True, verbose_name='\u8eab\u9ad8')),
                ('weight', models.CharField(blank=True, default='', help_text='\u5355\u4f4dkg', max_length=50, null=True, verbose_name='\u4f53\u91cd')),
                ('bust', models.CharField(blank=True, default='', help_text='\u5355\u4f4dcm', max_length=50, null=True, verbose_name='\u80f8\u56f4')),
                ('waist', models.CharField(blank=True, default='', help_text='\u5355\u4f4dcm', max_length=50, null=True, verbose_name='\u8170\u56f4')),
                ('hips', models.CharField(blank=True, default='', help_text='\u5355\u4f4dcm', max_length=50, null=True, verbose_name='\u81c0\u56f4')),
            ],
            options={
                'verbose_name': '\u7ea2\u4eba',
                'verbose_name_plural': '\u7ea2\u4eba',
            },
        ),
        migrations.CreateModel(
            name='CelebrityBackups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='Email')),
                ('sites', models.TextField(blank=True, default='', verbose_name='Sites')),
                ('gender', models.IntegerField(blank=True, default=1, null=True, verbose_name='Gender')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Country')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_join', models.BooleanField(default=True)),
                ('assign', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity_email', models.CharField(blank=True, default='', max_length=100, verbose_name='\u7ea2\u4eba\u90ae\u7bb1')),
                ('type', models.CharField(blank=True, choices=[('blog', 'Blog'), ('lookbook', 'Lookbook'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('polyvore', 'Polyvore'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest'), ('other', 'Other')], default=0, max_length=100, null=True, verbose_name='\u535a\u5ba2\u7c7b\u578b')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='\u535a\u5ba2\u94fe\u63a5')),
                ('profile', models.IntegerField(blank=True, default=0, null=True)),
                ('flow', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityContacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='Email')),
                ('sites', models.TextField(blank=True, default='', verbose_name='Sites')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='\u7ea2\u4eba\u90ae\u7bb1')),
                ('fee', models.FloatField(blank=True, default=0.0, verbose_name='Fee')),
                ('currency', models.CharField(blank=True, default='USD', max_length=50, verbose_name='\u5e01\u79cd')),
                ('pp_account', models.CharField(blank=True, default='', max_length=100, verbose_name='PP Account')),
                ('what_for', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='What for')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(blank=True, default='', max_length=100, verbose_name='\u8ba2\u5355\u53f7')),
                ('sku', models.CharField(blank=True, default='', max_length=100, verbose_name='SKU')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL')),
                ('show_date', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='Show Date')),
                ('celebrity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celebrities.Celebrits', verbose_name='\u7ea2\u4ebaID')),
            ],
        ),
        migrations.CreateModel(
            name='Flows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50, null=True, verbose_name='\u6570\u636e\u6765\u6e90')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='sku')),
                ('flow', models.IntegerField(null=True, verbose_name='\u6b21\u6570')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrities.Celebrits', verbose_name='celebrits_id')),
            ],
        ),
        migrations.CreateModel(
            name='Lookbook_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('star', models.IntegerField(null=True, verbose_name='\u661f\u7ea7')),
                ('types', models.IntegerField(null=True, verbose_name='0:lookbook; 1:product;')),
                ('created', models.IntegerField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customers', verbose_name='customer_id')),
            ],
        ),
        migrations.CreateModel(
            name='Lookbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='\u6807\u9898')),
                ('images', models.TextField(null=True, verbose_name='\u56fe\u7247\u540d')),
                ('created', models.IntegerField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('visibility', models.IntegerField(null=True, verbose_name='\u662f\u5426\u53ef\u89c1')),
            ],
        ),
        migrations.AddField(
            model_name='lookbook_reviews',
            name='lookbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrities.Lookbooks', verbose_name='looksbooks_id'),
        ),
    ]
