# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_unixdatetimefield.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=100, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u54c1\u724c',
                'verbose_name_plural': '\u54c1\u724c',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('link', models.CharField(default='', max_length=255, verbose_name='URL')),
                ('orderby', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Products order by')),
                ('desc', models.IntegerField(choices=[(0, '\u5012\u5e8f'), (1, '\u5347\u5e8f')], default=1, verbose_name='\u5347/\u5012\u5e8f')),
                ('visibility', models.IntegerField(choices=[(1, '\u53ef\u89c1'), (0, '\u4e0d\u53ef\u89c1')], default=1, verbose_name='\u662f\u5426\u53ef\u89c1')),
                ('on_menu', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=1, verbose_name='Listed on menu')),
                ('stereotyped', models.IntegerField(choices=[(1, '\u663e\u793a'), (0, '\u9690\u85cf')], default=1, verbose_name='Stereotyped modules')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('template', models.CharField(blank=True, max_length=100, verbose_name='\u5206\u7c7b\u6a21\u677f')),
                ('brief', models.TextField(blank=True, verbose_name='\u5206\u7c7b\u7b80\u4ecb')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
                ('hot_catalog', models.TextField(blank=True, default='', help_text='\u683c\u5f0f\uff1adresses,dresses-c-92', null=True, verbose_name='hot catalog & link')),
                ('is_brand', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=0, verbose_name='Is Brand')),
                ('price_ranges', models.CharField(blank=True, help_text="e.x: '5,7' means '(0,5],(5,7]' ", max_length=100, verbose_name='Price Ranges')),
                ('meta_title', models.CharField(blank=True, default='', max_length=100, verbose_name='SEO\u6807\u9898')),
                ('meta_keywords', models.TextField(blank=True, default='', null=True, verbose_name='SEO\u5173\u952e\u5b57')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='SEO\u63cf\u8ff0')),
                ('recommended_products', models.CharField(blank=True, default='', help_text="\u7528','\u9694\u5f00\uff0c\u5982\uff1a'CAAAFT2,BD000KTV,BD000KTX' ", max_length=100, verbose_name='\u63a8\u8350\u4ea7\u54c1sku')),
                ('image_src', models.ImageField(blank=True, default='', upload_to=products.models.get_category_image_upload_path, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('image_link', models.CharField(blank=True, default='', max_length=100, verbose_name='\u56fe\u7247\u94fe\u63a5')),
                ('image_alt', models.CharField(blank=True, default='', help_text='\u56fe\u7247\u65e0\u6cd5\u663e\u793a\u65f6\u5c06\u7528\u8be5\u6587\u5b57\u4ee3\u66ff', max_length=100, verbose_name='\u56fe\u7247\u6587\u672c')),
                ('image_map', models.TextField(blank=True, default='', verbose_name='Image Map')),
                ('pimage_src', models.ImageField(blank=True, default='', upload_to=products.models.get_category_image_upload_path, verbose_name='\u624b\u673a\u56fe\u7247\u5730\u5740')),
                ('position', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('is_filter', models.IntegerField(default=0, verbose_name='\u662f\u5426\u6709\u6392\u5e8f\u89c4\u5219')),
                ('pimage_map', models.TextField(blank=True, default='', verbose_name='\u624b\u673a\u7248Image Map')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('positiontwo', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u4ea7\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='CategorySorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(default='', max_length=40, verbose_name='SKU')),
                ('attributes', models.TextField(blank=True, default=False, null=True, verbose_name='\u5c5e\u6027')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.get_celebrity_image_upload_path, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('position', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('type', models.IntegerField(choices=[(1, '\u7ea2\u4eba'), (2, '\u5173\u8054'), (3, '\u7ea2\u4eba\u5173\u8054')], default=1, verbose_name='\u5173\u8054\u7c7b\u578b')),
                ('link_sku', models.CharField(blank=True, default='', help_text='\u4ea7\u54c1SKU\u9017\u53f7\u5206\u9694,type=1\u65f6\u4e3a\u7ea2\u4ebaid', max_length=150, null=True, verbose_name='\u5173\u8054SKU')),
                ('is_show', models.BooleanField(default=1, verbose_name='\u5c55\u793a')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
                ('celebrity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celebrities.Celebrits', verbose_name='celebrity_id')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('code', models.CharField(help_text='00-ZZ', max_length=2)),
                ('brief', models.TextField(blank=True, verbose_name='\u5206\u7c7b\u7b80\u4ecb')),
                ('status', models.BooleanField(default=True)),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Collection', verbose_name='\u7236\u7ea7\u5206\u7c7b')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('clicks', models.IntegerField(null=True)),
                ('quick_clicks', models.IntegerField(null=True)),
                ('add_times', models.IntegerField(null=True)),
                ('hits', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Mulit Select'), (1, 'One Select'), (2, 'Input')], default=0)),
                ('name', models.CharField(max_length=100)),
                ('options', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u8fc7\u6ee4',
                'verbose_name_plural': '\u4ea7\u54c1\u8fc7\u6ee4',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(blank=True, default='', max_length=122, null=True)),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True)),
                ('sku', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Marks')),
            ],
        ),
        migrations.CreateModel(
            name='OldProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('link', models.CharField(blank=True, default='', max_length=300, verbose_name='URL')),
                ('sku', models.CharField(max_length=200, unique=True, verbose_name='SKU')),
                ('price', models.FloatField(default=0.0, verbose_name='\u672c\u7ad9\u4ef7\u683c')),
                ('market_price', models.FloatField(default=0.0, verbose_name='\u5e02\u573a\u4ef7\u683c')),
                ('status', models.IntegerField(choices=[(1, '\u4e0a\u67b6'), (0, '\u4e0b\u67b6')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='\u4ea7\u54c1\u63cf\u8ff0')),
                ('weight', models.FloatField(default=0.0, help_text='\u57fa\u672c\u5355\u4f4d\u4e3aKG \u5343\u514b', verbose_name='\u4ea7\u54c1\u91cd\u91cf')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('deleted', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('store', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Store')),
                ('keywords', models.TextField(blank=True, default='', null=True, verbose_name='Keywords')),
                ('erp_item_id', models.BooleanField(choices=[(0, '\u672a\u6293\u5355'), (1, '\u5df2\u6293\u5355')], default=0)),
                ('cost', models.FloatField(default=0.0, verbose_name='\u603b\u6210\u672c')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='\u91c7\u8d2d\u6210\u672c')),
                ('stock', models.IntegerField(choices=[(-99, '\u4e0d\u9650\u5236'), (-1, '\u9650\u5236'), (0, '\u4e0d\u53ef\u552e')], default=-99, verbose_name='\u5e93\u5b58\u72b6\u6001')),
                ('brief', models.TextField(blank=True, default='', null=True, verbose_name='\u4ea7\u54c1\u8be6\u60c5')),
                ('display_date', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, db_index=True, null=True, verbose_name='\u5c55\u793a\u65f6\u95f4')),
                ('meta_title', models.CharField(blank=True, default='', max_length=100, verbose_name='SEO\u6807\u9898')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=100, verbose_name='SEO\u5173\u952e\u5b57')),
                ('meta_description', models.CharField(blank=True, default='', max_length=300, verbose_name='SEO\u63cf\u8ff0')),
                ('hits', models.IntegerField(default=0, verbose_name='\u8d2d\u4e70\u6b21\u6570')),
                ('type', models.IntegerField(choices=[(0, '\u57fa\u672c\u4ea7\u54c1'), (1, '\u914d\u7f6e\u4ea7\u54c1'), (2, '\u6253\u5305\u4ea7\u54c1'), (3, '\u7b80\u5355\u914d\u7f6e\u4ea7\u54c1')], default=3, verbose_name='\u4ea7\u54c1\u7c7b\u578b')),
                ('visibility', models.IntegerField(choices=[(1, '\u53ef\u89c1'), (0, '\u4e0d\u53ef\u89c1')], db_index=True, default=1, verbose_name='\u662f\u5426\u53ef\u89c1')),
                ('factory', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u4f9b\u8d27\u5546')),
                ('attributes', models.TextField(blank=True, default='', null=True, verbose_name='\u5c5e\u6027')),
                ('offline_factory', models.CharField(blank=True, default='', max_length=200, verbose_name='\u7ebf\u4e0b\u4f9b\u8d27\u5546')),
                ('offline_sku', models.CharField(blank=True, default='', max_length=50, verbose_name='\u7ebf\u4e0b\u4f9b\u8d27\u5546SKU')),
                ('taobao_url', models.CharField(blank=True, default='', max_length=500, verbose_name='\u6dd8\u5b9durl')),
                ('presell', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True, verbose_name='\u9884\u552e\u5230\u671f\u65f6\u95f4')),
                ('presell_message', models.CharField(blank=True, default='', max_length=100, verbose_name='\u9884\u552e\u6587\u6848')),
                ('filter_attributes', models.TextField(blank=True, default='', null=True, verbose_name='\u8fc7\u6ee4\u5c5e\u6027')),
                ('position', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('source', models.CharField(blank=True, choices=[('\u91c7\u8d2d', '\u91c7\u8d2d'), ('\u505a\u8d27', '\u505a\u8d27'), ('\u5e93\u5b58\u9650\u5236\u9500\u552e', '\u5e93\u5b58\u9650\u5236\u9500\u552e')], default='\u91c7\u8d2d', max_length=100, verbose_name='\u4f9b\u8d27\u6765\u6e90')),
                ('extra_fee', models.FloatField(default=0.0, verbose_name='\u4f4e\u5355\u4ef7\u4ea7\u54c1\u52a0\u6536\u8fd0\u8d39')),
                ('cn_name', models.CharField(blank=True, default='', max_length=100, verbose_name='\u4ea7\u54c1\u540d\u4e2d\u6587')),
                ('configs', models.TextField(blank=True, default='', null=True, verbose_name='\u4ea7\u54c1\u56fe\u7247\u5e8f\u5217\u5316\u6570\u636e\u4fdd\u5b58')),
                ('has_pick', models.IntegerField(default=0, verbose_name='\u53ef\u6311\u9009')),
                ('add_times', models.IntegerField(default=0)),
                ('default_catalog', models.CharField(blank=True, default='', max_length=10, verbose_name='\u9ed8\u8ba4\u5206\u7c7b')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Brands', verbose_name='\u54c1\u724c')),
                ('category', models.ManyToManyField(help_text='\u66f4\u6539\u4ea7\u54c1\u5206\u7c7b\u540e\uff0c\u8bf7\u7acb\u5373\u4fdd\u5b58', through='products.CategoryProduct', to='products.Category', verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('offline_picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_picker', to=settings.AUTH_USER_MODEL, verbose_name='\u9009\u6b3e\u4eba')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1',
                'verbose_name_plural': '\u4ea7\u54c1',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('options', models.TextField(blank=True, default='', help_text="\u4e0d\u540c\u5c3a\u7801\u4ee5','\u9694\u5f00")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.TextField(blank=True, default='', help_text='split by ,')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Filter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.get_product_image_upload_path, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5220\u9664')),
                ('suffix', models.CharField(default='jpg', max_length=100, verbose_name='\u56fe\u7247\u540e\u7f00\u540d')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u589e\u65f6\u95f4')),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('is_default', models.BooleanField(default=0, verbose_name='\u8bbe\u7f6e\u4e3a\u9ed8\u8ba4')),
                ('status', models.IntegerField(default=1, verbose_name='\u72b6\u6001')),
                ('type', models.IntegerField(default=1, verbose_name='\u7c7b\u578b')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='\u4ea7\u54c1\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u56fe\u7247',
                'verbose_name_plural': '\u4ea7\u54c1\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='Productitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '\u4e0b\u67b6'), (1, '\u4e0a\u67b6')], default=1, verbose_name='\u72b6\u6001')),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5c3a\u7801')),
                ('stock', models.IntegerField(default=-99, verbose_name='\u5e93\u5b58\u91cf')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Relatedproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_product_id', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=100, verbose_name='\u63cf\u8ff0')),
                ('label', models.CharField(max_length=100)),
                ('catemanger', models.CharField(max_length=100, verbose_name='\u54c1\u7c7b\u7ecf\u7406')),
            ],
            options={
                'verbose_name': '\u54c1\u7c7b',
                'verbose_name_plural': '\u54c1\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stocks', models.IntegerField(blank=True, default='')),
                ('isdisplay', models.IntegerField(default=1)),
                ('test', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TagProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True)),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('link', models.CharField(max_length=100, verbose_name='\u6807\u7b7eurl')),
                ('position', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, null=True)),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Trans_de',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('brief', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_es',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('brief', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_fr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('brief', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TransCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meta_title', models.CharField(blank=True, default='', max_length=100, verbose_name='SEO\u6807\u9898')),
                ('meta_keywords', models.TextField(blank=True, default='', null=True, verbose_name='SEO\u5173\u952e\u5b57')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='SEO\u63cf\u8ff0')),
                ('category_id', models.IntegerField(null=True)),
                ('lang', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=200)),
                ('weight', models.FloatField(default=0.0, help_text='KG')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(1, '\u53ef\u9500\u552e'), (0, '\u505c\u6b62\u9500\u552e')], default=1)),
                ('image', models.ImageField(upload_to=products.models.get_product_image_upload_path)),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True)),
                ('updated', django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='tagproduct',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='set',
            field=models.ForeignKey(blank=True, help_text='\u66f4\u6539\u4ea7\u54c1set\u540e\uff0c\u8bf7\u7acb\u5373\u4fdd\u5b58', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Set', verbose_name='\u54c1\u7c7b'),
        ),
        migrations.AddField(
            model_name='marks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='daily',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='celebrityimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, to='products.Filter'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Category', verbose_name='\u7236\u7ea7\u5206\u7c7b'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set([('key', 'product')]),
        ),
    ]
