# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.IntegerField(default=0, help_text='\u6570\u5b57\u8d8a\u5c0f\u6392\u5e8f\u8d8a\u9760\u524d', verbose_name='\u56fe\u7247\u6392\u5e8f'),
        ),
    ]
