# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='USD\u6210\u672c'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_date',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, db_index=True, null=True, verbose_name='\u4e0a\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_cost',
            field=models.FloatField(default=0.0, verbose_name='RMB\u6210\u672c'),
        ),
    ]
